AFP/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.core import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^ahorros$', views.AhorrosPageView.as_view(), name='ahorros'),
    url(r'^rentabilidad$', views.RentabilidadPageView.as_view(), name='rentabilidad'),
    url(r'^resultados$', views.ResultadosPageView.as_view(), name='resultados'),
    url(r'^signup$', views.signupView, name='signup'),
    url(r'^login$', 'django.contrib.auth.views.login',
        {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login',
        name='logout'),
]

apps/core/urls.py
from django.conf.urls import patterns, url
from apps.core import views

urlpatterns = \
    patterns('',

             url(r'^home/', views.HomePageView.as_view(), name='home'),

             )

apps/core/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth import models as auth_models
# Create your models here.


class TipoCatalogo(models.Model):

    nombre = models.CharField(max_length=30)

    def __unicode__(self):
        return self.nombre


class Catalogo(models.Model):

    tipo_catalogo = models.ForeignKey(TipoCatalogo)
    numero_dato = models.CharField(max_length=5)
    dato = models.CharField(max_length=100)
    abreviatura = models.CharField(max_length=5,null=True,blank=True)
    valor1 = models.CharField(max_length=30,null=True,blank=True)
    valor2 = models.CharField(max_length=30,null=True,blank=True)

    def __unicode__(self):
        return self.dato


class Persona(models.Model):

    dni = models.CharField(max_length=15, unique=True)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    estado_civil = models.ForeignKey(Catalogo, related_name="estado_civil",null=True,blank=True)
    fecha_nacimiento = models.DateField(null=True,blank=True)
    sexo = models.ForeignKey(Catalogo, related_name="sexo",null=True,blank=True)
    usuario = models.ForeignKey(auth_models.User, unique=True)

    def __unicode__(self):
        return self.nombre +" " + self.apellido


class Fondo(models.Model):
    persona = models.ForeignKey(Persona, unique=True)
    ahorro = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    tipo_fondo = models.ForeignKey(Catalogo, related_name="tipo_fondo",null=True,blank=True)
    tea = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


class Aportacion(models.Model):
    fondo = models.ForeignKey(Fondo, unique=True, null=True, blank=True)
    sueldo = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_inicio = models.DateField(null=True, blank=True)
    fecha_fin = models.DateField(null=True, blank=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2)

apps/core/forms.py
# -- coding: utf-8 --
from django import forms
from django.contrib.auth.models import User
import models
import constants


class RegistrationForm(forms.Form):
    email = forms.EmailField(max_length=50, )
    username = forms.CharField(max_length=30)
    password = forms.PasswordInput()
    # rest of the fields

    def save(self):
        cleaned_data = super(RegistrationForm, self).clean()
        user = User()
        user.email = cleaned_data.get("username")
        user.username = cleaned_data.get("username")
        user.save(False)
        user.set_password = self.data.get("password")
        user.save()

        return user
        # you can validate those here

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("El usuario ya existe.")


    class Meta:
        model = User


class PersonaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PersonaForm, self).__init__(*args, **kwargs)
        self.fields['sexo'].queryset = models.Catalogo.objects.filter(tipo_catalogo=constants.ID_SEXO)
        self.fields['estado_civil'].queryset = models.Catalogo.objects.filter(tipo_catalogo=constants.ID_ESTADO_CIVIL)

        for field, campo in self.fields.iteritems():
            if field == 'fecha_nacimiento':
                campo.widget.attrs['class'] = 'datepicker form-control'
                campo.widget.attrs['maxlength'] = '10'
                campo.input_formats = ('%d/%m/%Y',)
            else:
                if field == 'dni':
                    campo.widget.attrs['class'] = 'numero doi form-control'
                else:
                    campo.widget.attrs['class'] = 'form-control'

    class Meta:
        model = models.Persona
        fields = '__all__'


class FondoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FondoForm, self).__init__(*args, **kwargs)
        self.fields['tipo_fondo'].queryset = models.Catalogo.objects.filter(tipo_catalogo=constants.ID_TIPO_FONDO)

        for field, campo in self.fields.iteritems():

            if field in ['ahorro','tea']:
                campo.widget.attrs['class'] = 'numero form-control'
            else:
                campo.widget.attrs['class'] = 'form-control'

    class Meta:
        model = models.Fondo
        fields = '__all__'


class AportacionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AportacionForm, self).__init__(*args, **kwargs)
        self.fields['monto'].widget.attrs['readonly'] = ""

        for field, campo in self.fields.iteritems():
            if field in ['fecha_inicio', 'fecha_fin']:
                campo.widget.attrs['class'] = 'datepicker form-control'
                campo.widget.attrs['maxlength'] = '10'
                campo.input_formats = ('%d/%m/%Y',)
            else:
                if field == 'monto':
                    campo.widget.attrs['class'] = 'numero form-control'
                else:
                    campo.widget.attrs['class'] = 'form-control'

    class Meta:
        model = models.Aportacion
        fields = '__all__'

apps/core/views.py
import  json
# Create your views here.
from decimal import Decimal
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django import http

# Create your views here.
from django.conf import settings
from django.views.generic import TemplateView, View

from .forms import RegistrationForm, PersonaForm, FondoForm, AportacionForm
from .models import Persona, Fondo, Aportacion, Catalogo
import constants


class AuthenticatedView(TemplateView):
    """Class for a view with login required"""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return redirect(settings.LOGIN_URL)

        return super(AuthenticatedView, self).dispatch(request,
                *args, **kwargs)


class JSONResponseMixin(object):
    """Class for a view thats only response in json format"""

    @classmethod
    def get_json_response(cls, content, **httpresponse_kwargs):
        """Construct a 'HttpResponse' object"""
        return http.HttpResponse(content, content_type='application/json',
                                 **httpresponse_kwargs)

    @classmethod
    def convert_context_to_json(cls, context):
        """Convert the context dictionary into a JSON object"""
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        if context:
            return json.dumps(context)
        else:
            return ''

    def render_to_response(self, context):
        """Returns a JSON response containing 'context' as payload"""
        return self.get_json_response(self.convert_context_to_json(context))


class HomePageView(AuthenticatedView):
    template_name = 'core/datos.html'
    persona_form = None
    mensaje = ""

    def get(self, request, tipo=None, *args, **kwargs):

        if request.user.is_authenticated():
            personas = Persona.objects.filter(usuario=request.user)
            if personas:
                self.persona_form = PersonaForm(instance=personas.first())
            else:
                self.persona_form = PersonaForm()
                self.persona_form.initial['usuario'] = request.user.id

            if 'fecha_nacimiento' in self.persona_form.initial.keys():
                    self.persona_form.initial['fecha_nacimiento'] = self.persona_form.initial['fecha_nacimiento'].strftime('%d/%m/%Y')
        else:
            redirect('login')
        result = self.render_to_response(self.get_context_data())
        return result

    def post(self, request, tipo=None):
        personas = Persona.objects.filter(usuario=request.user)
        if personas:
            self.persona_form = PersonaForm(request.POST,instance=personas.first())
        else:
            self.persona_form = PersonaForm(request.POST)

        if self.persona_form.is_valid():
            self.persona_form.save()
            self.mensaje = "Se guardo satisfactoriamente"

        result = self.render_to_response(self.get_context_data())
        return result

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['persona_form'] = self.persona_form
        context['mensaje'] = self.mensaje

        return context


def calcular_ahorro(aporte):
    tea = aporte.fondo.tea/100
    tem = ((1+tea) ** Decimal(30.0/360.0)) - 1
    n = (aporte.fecha_fin - aporte.fecha_inicio).days//30
    monto = aporte.monto
    ahorro_num = (1+tem) ** n - 1
    ahorro = monto*(ahorro_num/tem)
    return round(ahorro,2)


class AhorrosPageView(AuthenticatedView):
    template_name = 'core/ahorros.html'
    fondo_form = None
    aportacion_form = None
    mensaje = ""
    por_aportacion = Catalogo.objects.filter(tipo_catalogo=constants.ID_APORTACION)[0]

    def get(self, request, tipo=None, *args, **kwargs):

        if request.user.is_authenticated():
            personas = Persona.objects.filter(usuario=request.user)
            if personas:
                persona = personas.first()
            else:
                redirect('home')

            fondos = Fondo.objects.filter(persona=persona)
            if fondos:
                fondo = fondos.first()
                self.fondo_form = FondoForm(instance=fondo)
                aportaciones = Aportacion.objects.filter(fondo=fondo)
                if aportaciones:
                    aportacion = aportaciones.first()
                    self.aportacion_form = AportacionForm(instance=aportacion)
                else:
                    self.aportacion_form = AportacionForm()
            else:
                self.fondo_form = FondoForm()
                self.fondo_form.initial['ahorro'] = 0
                self.fondo_form.initial['persona'] = persona
                self.aportacion_form = AportacionForm()

            if 'fecha_inicio' in self.aportacion_form.initial.keys():
                self.aportacion_form.initial['fecha_inicio'] = self.aportacion_form.initial['fecha_inicio'].strftime('%d/%m/%Y')
            if 'fecha_fin' in self.aportacion_form.initial.keys():
                self.aportacion_form.initial['fecha_fin'] = self.aportacion_form.initial['fecha_fin'].strftime('%d/%m/%Y')

        else:
            redirect('login')

        result = self.render_to_response(self.get_context_data())
        return result

    def post(self, request, tipo=None):
        if request.user.is_authenticated():
            personas = Persona.objects.filter(usuario=request.user)
            if personas:
                persona = personas.first()
            else:
                redirect('home')

            fondos = Fondo.objects.filter(persona=persona)
            if fondos:
                fondo = fondos.first()
                self.fondo_form = FondoForm(request.POST, instance=fondo)
                aportaciones = Aportacion.objects.filter(fondo=fondo)
                if aportaciones:
                    aportacion = aportaciones.first()
                    self.aportacion_form = AportacionForm(request.POST, instance=aportacion)
                else:
                    self.aportacion_form = AportacionForm(request.POST,)
            else:
                self.fondo_form = FondoForm(request.POST,)
                self.aportacion_form = AportacionForm(request.POST,)

            if self.fondo_form.is_valid():
                fondo = self.fondo_form.save()
                if self.aportacion_form.is_valid():
                    aportacion = self.aportacion_form.save(False)
                    aportacion.fondo = fondo
                    aportacion.save()
                    fondo.ahorro = calcular_ahorro(aportacion)
                    fondo.save()
                    self.mensaje = "Se guardo satisfactoriamente"
                else:
                    self.mensaje = "No de pudo guardar intentelo mas tarde"
            else:
                self.mensaje = "No de pudo guardar intentelo mas tarde"
                print fondo.errors

        else:
            redirect('login')
        result = self.render_to_response(self.get_context_data())
        return result

    def get_context_data(self, **kwargs):
        context = super(AhorrosPageView, self).get_context_data(**kwargs)
        context['fondo_form'] = self.fondo_form
        context['aportacion_form'] = self.aportacion_form
        context['mensaje'] = self.mensaje
        context['por_aportacion'] = self.por_aportacion

        return context


class RentabilidadPageView(AuthenticatedView):
    template_name = 'core/rentabilidad.html'


class ResultadosPageView(AuthenticatedView):
    template_name = 'core/resultados.html'


def signupView(request):
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)

            return redirect('home')

        else:
            return render(request, "core/signup.html", {'form': form})

    else:
        if request.user.is_authenticated():
            return redirect('home')
        else:
            return render(request, "core/signup.html", )

templates/core/ahorros.html
{% extends "core/principal.html" %}
{% load humanize %}
{% load staticfiles %}
{% block detalle %}

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                {% if mensaje %}
                    <div class="col-lg-12">
                        <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <i class="fa fa-check-circle"></i>  <strong>EXITOSO</strong> {{ mensaje }}
                        </div>
                    </div>
                {% endif %}
                <form class="form-horizontal " role="form" action="{% url 'ahorros' %}" method="post">
                    {% csrf_token %}

                    <div class="col-lg-12">
                        <h1 class="page-header">
                            APORTACIONES <small>Vista usuario</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Fondo de pensiones
                            </li>
                        </ol>

                    </div>
                    {% if fondo_form.errors %}
                        <span class="label label-danger">CAMPOS REQUERIDOS...</span>
                    {% endif %}
                    <div class="form-group col-sm-12">
                        <label class="col-sm-1 control-label">Tipo de fondo</label>
                        <div class="col-sm-2 {% if fondo_form.tipo_fondo.errors %} has-error {% endif %}">
                            {{ fondo_form.tipo_fondo }}
                        </div>
                        <label class="col-sm-1 control-label ">T E A</label>
                        <div class="col-sm-2 {% if fondo_form.tea.errors %} has-error {% endif %}">
                            {{ fondo_form.tea }}
                        </div>
                        <label class="col-sm-1 control-label ">Ahorros</label>
                        <div  class="col-sm-5 alert-info">
                            <h3 align="center"><strong>S/ {{ fondo_form.instance.ahorro }}</strong></h3>
                        </div>
                        <div class="hide col-sm-1">
                            {{ fondo_form.persona }}
                        </div>

                    </div>
                    {% if aportacion_form.errors %}
                        <span class="label label-danger">CAMPOS REQUERIDOS...</span>
                    {% endif %}
                    <div class="form-group col-sm-12">
                        <label class="col-sm-1 control-label">Sueldo</label>
                        <div class="col-sm-2 {% if aportacion_form.sueldo.errors %} has-error {% endif %}">
                            {{ aportacion_form.sueldo }}
                        </div>
                        <label class="col-sm-1 control-label ">Fecha Ini.</label>
                        <div class="col-sm-2 {% if aportacion_form.fecha_inicio.errors %} has-error {% endif %}">
                            {{ aportacion_form.fecha_inicio }}
                        </div>
                        <label class="col-sm-1 control-label ">Fecha Fin.</label>
                        <div class="col-sm-2 {% if aportacion_form.fecha_fin.errors %} has-error {% endif %}">
                            {{ aportacion_form.fecha_fin }}
                        </div>
                        <label class="col-sm-1 control-label ">Monto</label>
                        <div class="col-sm-2 {% if aportacion_form.monto.errors %} has-error {% endif %}">
                            {{ aportacion_form.monto }}
                        </div>


                    </div>
                    <div class="form-group col-sm-12">
                        <div class="col-sm-offset-8 col-md-4">
                            <button type="submit" class="btn btn-success" onclick="return confirm('¿Desea guardar los cambios?')">Guardar</button>
                        </div>

                    </div>
                </form>
            </div>
            <!-- /.row -->


            <!-- /.row -->

        </div>
                <!-- /.container-fluid -->

    </div>

    <script>
        window.onload = function() {
            $("#ahorros").addClass('active');
            $('.datepicker').datepicker({
                format: "dd/mm/yyyy"
            });
            $("#id_sueldo").keyup(function(){
                var sueldo = parseFloat($("#id_sueldo").val());
                por_aport = parseInt("{{ por_aportacion }}");
                $("#id_monto").val((sueldo*por_aport/100).toFixed(2));
            });
        };
    </script>
    <!-- Morris Charts JavaScript -->
{% endblock %}

templates/core/datos.html
{% extends "core/principal.html" %}
{% load humanize %}
{% load staticfiles %}

{% block detalle %}

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                {% if mensaje %}
                <div class="col-lg-12">
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <i class="fa fa-check-circle"></i>  <strong>EXITOSO</strong> {{ mensaje }}
                    </div>
                </div>
                {% endif %}
                <form class="form-horizontal " role="form" action="{% url 'home' %}" method="post">
                    {% csrf_token %}
                    {% if persona_form.errors %}
                        <span class="label label-danger">CAMPOS REQUERIDOS...</span>
                    {% endif %}
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            MIS DATOS <small>Vista usuario</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Mis Datos
                            </li>
                        </ol>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-1 control-label">DNI</label>
                        <div class="col-sm-2 {% if persona_form.dni.errors %} has-error {% endif %}">
                            {{ persona_form.dni }}
                        </div>
                        <label class="col-sm-1 control-label ">Fecha Nac.</label>
                        <div class="col-sm-2 {% if persona_form.fecha_nacimiento.errors %} has-error {% endif %}">
                            {{ persona_form.fecha_nacimiento }}
                        </div>
                        <label class="col-sm-1 control-label ">Nombres</label>
                        <div class="col-sm-5 {% if persona_form.nombre.errors %} has-error {% endif %}">
                            {{ persona_form.nombre }}
                        </div>
                        <div class="hide col-sm-1">
                            {{ persona_form.usuario }}
                        </div>

                    </div>

                    <div class="form-group col-sm-12">
                        <label class="col-sm-1 control-label"> Sexo </label>
                        <div class="col-sm-2 {% if persona_form.sexo.errors %} has-error {% endif %}">
                            {{ persona_form.sexo }}
                        </div>
                        <label class="col-sm-1 control-label">Estado civil</label>
                        <div class="col-sm-2 {% if persona_form.estado_civil.errors %} has-error {% endif %}">
                            {{ persona_form.estado_civil }}
                        </div>
                        <label class="col-sm-1 control-label">Apellidos</label>
                        <div class="col-sm-5 {% if persona_form.apellido.errors %} has-error {% endif %}">
                            {{ persona_form.apellido }}
                        </div>

                    </div>
                    <div class="form-group col-sm-12">
                        <div class="col-sm-offset-8 col-md-4">
                            <button type="submit" class="btn btn-success" onclick="return confirm('¿Desea guardar los cambios?')">Guardar</button>
                        </div>

                    </div>
                </form>
            </div>
            <!-- /.row -->


            <!-- /.row -->

        </div>
                <!-- /.container-fluid -->

    </div>

    <script>
        window.onload = function() {
            $("#datos").addClass('active');
            $('.datepicker').datepicker({
                format: "dd/mm/yyyy"
            });
        };
    </script>

    <!-- Morris Charts JavaScript -->
{% endblock %}

templates/core/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    
    <nav id="head" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    
        <div class="container-fluid ">
            
            <div class="navbar-header">
                
                <a href="{% url 'home' %}" class="navbar-brand" ><span class="icon-dollar"></span> UPC - AFP</a>
                
            </div>
            <div class="collapse navbar-collapse ">
                
                {% block menu %}
                {% endblock %}

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          <i class = "icon-user"></i>
                          {{ user.username }}
                          <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">

                        <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                      </ul>
                    </li>
                </ul>
                {% block menu_princ %}
                {% endblock %}
                

            </div>
        </div>
    
    </nav>

    {% block contenido %}
    {% endblock %}
    {% block extrawindows %}
    {% endblock %}

{% endblock %}

templates/core/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrahead %} 
	<link rel="stylesheet" media="screen" href="{% static 'css/login.css' %}" >
	
{% endblock %}
{% block content %}
    <style>
body  {
    background-image: url({% static 'images/fondo7.jpg' %});
    background-size: 100% 100%;
}
</style>
	<div>
		<div class="container " >
			<div class="grid fluid">

				<div class="row ">
					<div class="col-lg-2">

	                </div>
					<div class="col-lg-8">
						<div class="">
							<div class="row">
								<div class="col-lg-6">
	                                <p align="center">
	                                    <br><br>
	                                    <img   src="{% static 'images/page.png' %}" alt="Generic placeholder image" style="width: 350px; height: 379px;">
	                                </p>
	                            </div>
								<div class="col-lg-6">
									<h1>
										<i class="fa fa-inverse fa-money white" ></i>
										<span style="color:#ffffff">AFP - UPC</span>
									</h1>
									<br>
									
									{% if error  %}
										<div class="row-bordered bg-spink">
											<div class="row">
												<div class="col-lg-1 text-center">
													<i class="icon-warning fg-amber"></i>
												</div>
												<div class="col-lg-11">
													{{ error }}
												</div>
											</div>
										</div>
									{% else %}
									 <div style="color:#ffffff; font-weight:600">Por favor ingrese los datos solicitados</div><br><br>
									{% endif %}
                                    {% block form %}
									<form  method="POST" action="{% url 'django.contrib.auth.views.login' %}">
										{% csrf_token %}
										<div class="row">
											<div class="col-lg-12 text-left">Usuario</div>
										</div>

										<div class="row">
											<div class="col-lg-12 text-left">
											    <input class="form-control text" type="text" name="username" placeholder=""  required tabindex="1">
											</div>
										</div>

										<div class="row">
											<div class="col-lg-12 text-left">Contraseña</div>
										</div>

										<div class="row">
											<div class="col-lg-12 text-left">
											    <input class="form-control" type="password" name="password" placeholder="" required tabindex="2"/>
											</div>
										</div>

										<div class="row">
											<div class="col-lg-6 text-left">
												
											</div>
											<div class="col-lg-6 text-right" ><br>
												<button type="submit" class="btn-danger" ><strong>Ingresar</strong></button>
											</div>
										</div>

										<div class="row">
											<div class="col-lg-12 text-left"><br>
												<small><span class="text-muted" >¿Aun no tiene una cuenta? </span><a href="{% url 'signup' %}" class="fg-darkBlue">Registrate</a></small>
											</div>
										</div>

									
									</form>
                                    {% endblock %}
								</div>	
							</div>
						</div>
					</div>
					
				</div>
				
			</div>
		</div>
	</div>

{% endblock %}

templates/core/principal_a.html
{% extends "core/home.html" %}
{% load humanize %}
{% load staticfiles %}
{% block contenido %}
<style type="text/css">
    .bg{
        width: 150px;
        height: 200px;
        margin: 10px;
        float: left;
        color: #fff;
        text-shadow: 2px 2px 2px #000;
        display: block;
        text-align: center;
    }
    body  {
        background-image: url({% static 'images/fondo7.jpg' %});
        background-size: 100% 100%;
    }


</style>

<!--<div class="form">-->

<div class="container">
    <div class="row">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix ">
                <li class="active">
                    <a href="#overview">
                        <i class="icon-chevron-right" ></i>
                        MIS DATOS </a>
                </li>
                <li class=""><a href="#transitions"><i class="icon-chevron-right"></i> MIS AHORROS</a></li>
                <li class=""><a href="#transitions"><i class="icon-chevron-right"></i> MI FAMILIA</a></li>
                <li class=""><a href="#transitions"><i class="icon-chevron-right"></i> RENTABILIDAD</a></li>
                <li class=""><a href="#transitions"><i class="icon-chevron-right"></i> RESULTADOS</a></li>

            </ul>
        </div>
    </div>
</div>



	
{% endblock %}

templates/core/rentabilidad.html
{% extends "core/principal.html" %}
{% load humanize %}
{% load staticfiles %}
{% block detalle %}

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        RENTABILIDAD <small>Vista usuario</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li class="active">
                            <i class="fa fa-dashboard"></i> Rentabilidad
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->


            <!-- /.row -->

        </div>
                <!-- /.container-fluid -->

    </div>

    <script>
        window.onload = function() {
            $("#rentabilidad").addClass('active');
        };
    </script>
    <!-- Morris Charts JavaScript -->
{% endblock %}

templates/core/resultados.html
{% extends "core/principal.html" %}
{% load humanize %}
{% load staticfiles %}
{% block detalle %}

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        RESULTADOS <small>Vista usuario</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li class="active">
                            <i class="fa fa-dashboard"></i> Resultados
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->


            <!-- /.row -->

        </div>
                <!-- /.container-fluid -->

    </div>

    <script>
        window.onload = function() {
            $("#resultados").addClass('active');
        };
    </script>
    <!-- Morris Charts JavaScript -->
{% endblock %}